### PR TITLE
Upgrade to Druid 0.15 and Spark 2.4 with dataframe api

### PR DESCRIPTION
**Pull request by drnushooz**
**Summary**
This PR does the following
1. Migrate to Druid version 0.15.1
2. Migrate to Spark 2.4 and use spark-avro package to add support for parquet avro.
3. Refactor the code to make it more modular.
4. Add a custom serializer for map type so that druid and Kryo can work well together without issues. 

**Validation steps**
Added unit tests and tested for buildability and unit tests using `sbt clean test`

### CODE REVIEW

**Comment by Gauravshah** [comment]
@drnushooz are you still using it ?
Does it work with newer version of druid ?

**Comment by drnushooz** [comment]
> @drnushooz are you still using it ?
> 
> Does it work with newer version of druid ?

I can update this to use Spark 3.5. No one seemed to want to use it but if you'd like, I can update it.

**Comment by Gauravshah** [comment]
Thanks, that would be great, we can give it a shot

**Comment by drnushooz** [comment]
> Thanks, that would be great, we can give it a shot

Sounds great. I will create a new branch for Spark 3.5 and share it with you. Stay tuned on this thread. Which version of Druid and Spark are yall using?

**Comment by Gauravshah** [comment]
@drnushooz just to clarify I was looking for newer version of druid ( I am ok with older version of spark )

**Comment by Gauravshah** [comment]
we are currently on druid 0.18, but we have initiated work to migrate it to 0.28, will probably take us 10 weeks before we get there.

**Comment by drnushooz** [comment]
> we are currently on druid 0.18, but we have initiated work to migrate it to 0.28, will probably take us 10 weeks before we get there.

I can use Druid 0.28 and would highly recommend using Spark 3.5. I did an upgrade for another enterprise app and the performance improvements are 4x to 8x depending on the workload. These are specific to Apache Arrow and better query planning.

**Comment by Gauravshah** [comment]
wow, we can definitely do that

**Pull request closed without merging**
